// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnAXSz0OwIv4t3-ZqA285vu268GvcUnLw',
    appId: '1:785606608903:web:b545b422e93880d21142a2',
    messagingSenderId: '785606608903',
    projectId: 'e-commerce-8970b',
    authDomain: 'e-commerce-8970b.firebaseapp.com',
    storageBucket: 'e-commerce-8970b.appspot.com',
    measurementId: 'G-YXMQ31JT26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfF1gxpvzQ-rQd_k8IspyaU4tbuOWGoDw',
    appId: '1:785606608903:android:4957615d0359ce311142a2',
    messagingSenderId: '785606608903',
    projectId: 'e-commerce-8970b',
    storageBucket: 'e-commerce-8970b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnriO_CL1hrb7qQJt3LP8rKngj3cLcHkk',
    appId: '1:785606608903:ios:8c28f7fa48d6af761142a2',
    messagingSenderId: '785606608903',
    projectId: 'e-commerce-8970b',
    storageBucket: 'e-commerce-8970b.appspot.com',
    iosBundleId: 'com.example.eCommereceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnriO_CL1hrb7qQJt3LP8rKngj3cLcHkk',
    appId: '1:785606608903:ios:8c28f7fa48d6af761142a2',
    messagingSenderId: '785606608903',
    projectId: 'e-commerce-8970b',
    storageBucket: 'e-commerce-8970b.appspot.com',
    iosBundleId: 'com.example.eCommereceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnAXSz0OwIv4t3-ZqA285vu268GvcUnLw',
    appId: '1:785606608903:web:50f1579984d8790f1142a2',
    messagingSenderId: '785606608903',
    projectId: 'e-commerce-8970b',
    authDomain: 'e-commerce-8970b.firebaseapp.com',
    storageBucket: 'e-commerce-8970b.appspot.com',
    measurementId: 'G-1W4SYKCJR4',
  );
}
